name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          # write SSH key to file
          echo "$SSH_KEY" > key.pem
          chmod 400 key.pem

          # SSH vào EC2 và deploy
          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST '
            cd my-devops-app &&
            git pull origin main &&
            npm install &&
            pm2 restart my-app || pm2 start index.js --name my-app
          '